name = "Fabulously Optimized"
author = "robotkoer"
version = "6.1.0-beta.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b81375e440fb7dfcd4efd0ac94c1fe406c3ab6c4857f0320fc9ec0d9ed21b710"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
