name = "Fabulously Optimized"
author = "robotkoer"
version = "6.1.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ab5c355cbccc94907ffe28cecb4cf0ba88303f319a704a955d311e6589df70b"

[versions]
fabric = "0.15.11"
minecraft = "1.21.1"
