name = "Fabulously Optimized"
author = "robotkoer"
version = "6.1.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "621869cdc6d80590822b629cb3243211a2034de75b4367b0e2c30e039a73bc2f"

[versions]
fabric = "0.15.11"
minecraft = "1.21.1"
