name = "Fabulously Optimized"
author = "robotkoer"
version = "6.1.0-beta.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "521a0af778396cc3dae80c9f1488550d9e9e16329b308164bc1515ced7988a35"

[versions]
fabric = "0.16.5"
minecraft = "1.21.1"
