name = "Fabulously Optimized"
author = "robotkoer"
version = "6.1.0-beta.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d5c628d61f72ab268af0d27f85d8ca976afd7454807567a90781945d17aa950"

[versions]
fabric = "0.16.2"
minecraft = "1.21.1"
