name = "Fabulously Optimized"
author = "robotkoer"
version = "6.1.0-beta.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "faea10a0fd3aa3055c93ae74ecdfa3a799ef755ea3ced61bc7ed69f2b4bbc3fd"

[versions]
fabric = "0.16.3"
minecraft = "1.21.1"
